### ISSUE TITLE
Cancelling or deleting active projects fails

### ISSUE THREAD

**Issue by peendebak** [QuTech-Delft/quantuminspire#128]
# Bug report

Make sure you are using the latest stable version.

## What did you try to do?

I tried to delete all currently queued jobs with the following code:
```
api=QI.get_api()
jj=api.get_jobs()

active_jobs=[j for j in jj if j['status']=='NEW']
print(f'{len(active_jobs)} new jobs')
[api.delete_job(j['id']) for j in active_jobs]
```

## What did you expect to happen?

All active jobs should be cancelled (or deleted)

## What actually happened?

An exception was generated
```
In [72]: api=QI.get_api()
    ...: jj=api.get_jobs()
    ...: 
    ...: active_jobs=[j for j in jj if j['status']=='NEW']
    ...: print(f'{len(active_jobs)} new jobs')
    ...: [api.delete_job(j['id']) for j in active_jobs]
8 new jobs
Traceback (most recent call last):

  File "C:\Users\EENDEB~1\AppData\Local\Temp/ipykernel_24080/4007034165.py", line 6, in <module>
    [api.delete_job(j['id']) for j in active_jobs]

  File "C:\Users\EENDEB~1\AppData\Local\Temp/ipykernel_24080/4007034165.py", line 6, in <listcomp>
    [api.delete_job(j['id']) for j in active_jobs]

  File "c:\projects\quantuminspire\src\quantuminspire\api.py", line 480, in delete_job
    return dict(self._action(['jobs', 'delete'], params={'id': job_id}))

TypeError: 'NoneType' object is not iterable
```

## Environment

Please specify:
* operating system, version and distribution: Windows
* python version (`python --version`) and distribution: 3.8

@QFer

**Comment by QFer** [comment]
@peendebak The api of jobs delete returns None instead of a dictionary (compare projects delete).

**Comment by QFer** [comment]
Solved by https://github.com/QuTech-Delft/quantuminspire/pull/130
