### ISSUE TITLE
QI "validation error" only on Ubuntu 19.04

### ISSUE THREAD

**Issue by jwoehr** [QuTech-Delft/quantuminspire#69]
# Bug report

>Make sure you are using the latest stable version.

Well, actually, I'm not, I'm cloning `master`.

## What did you try to do?

I have QI (master branch) running on x86_64 Ubuntu 18.04 and Power9 CentOS 7.

I've added support for QI to my open source project [Qis Job](https://github.com/jwoehr/qis_job/) and Qis Job works fine in conjunction with QI on those two platforms. All the jobs for my account on Quantum Inspire have been run that way.

I've just installed QI on Ubuntu 19.04 and when I try to run the Qis Job program to send QI one or more qasm jobs (which works fine on the other two platforms) I get a traceback.

## What did you expect to happen?

I expected my jobs to run as they do on my other two installed platforms.

## What actually happened?
```
$ python qasm_job.py --api_provider=QI  qasm_examples/yiqing.qasm 
Traceback (most recent call last):
  File "qasm_job.py", line 390, in <module>
    BACKEND_NAME, SIM, QUBITS)
  File "qasm_job.py", line 150, in choose_backend
    provider = account_fu(token, url)
  File "qasm_job.py", line 118, in account_fu
    provider = qi_account_fu(token)
  File "qasm_job.py", line 104, in qi_account_fu
    from quantuminspire.qiskit import QI
  File "/home/jwoehr/work/Qiskit/quantuminspire/src/quantuminspire/qiskit/__init__.py", line 1, in <module>
    from quantuminspire.qiskit.quantum_inspire_provider import QuantumInspireProvider
  File "/home/jwoehr/work/Qiskit/quantuminspire/src/quantuminspire/qiskit/quantum_inspire_provider.py", line 8, in <module>
    from quantuminspire.qiskit.backend_qx import QuantumInspireBackend
  File "/home/jwoehr/work/Qiskit/quantuminspire/src/quantuminspire/qiskit/backend_qx.py", line 41, in <module>
    class QuantumInspireBackend(BaseBackend):  # type: ignore
  File "/home/jwoehr/work/Qiskit/quantuminspire/src/quantuminspire/qiskit/backend_qx.py", line 55, in QuantumInspireBackend
    max_experiments=1
  File "/home/jwoehr/work/Qiskit/DEV/qiskit-terra/qiskit/validation/base.py", line 253, in _decorated
    ex.messages, ex.field_names, ex.fields, ex.data, **ex.kwargs) from None
qiskit.validation.exceptions.ModelValidationError: {'coupling_map': ['Missing data for required field.']}
```
## Environment

Please specify:
* operating system, version and distribution:
```
Linux Leno 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ more /etc/os-release
NAME="Ubuntu"
VERSION="19.04 (Disco Dingo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.04"
VERSION_ID="19.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```
* python version (`python --version`) and distribution:
```
$ python --version
Python 3.7.3
```
from `apt`:
```
python3/disco,now 3.7.3-1 amd64 [installed]
```
* list of installed packages (`pip list` or equivalent):
```
$ pip list
Package                Version     Location                                           
---------------------- ----------- ---------------------------------------------------
apturl                 0.5.2       
asn1crypto             0.24.0      
atomicwrites           1.3.0       
attrs                  19.1.0      
backcall               0.1.0       
bleach                 3.1.0       
blinker                1.4         
Brlapi                 0.6.7       
certifi                2018.8.24   
chardet                3.0.4       
command-not-found      0.3         
coreapi                2.3.3       
coreschema             0.0.4       
coverage               4.5.4       
cryptography           2.3         
cupshelpers            1.0         
cvxopt                 1.2.3       
cycler                 0.10.0      
Cython                 0.29.12     
decorator              4.4.0       
defer                  1.0.6       
defusedxml             0.6.0       
distro                 1.3.0       
distro-info            0.21ubuntu2 
dlx                    1.0.4       
docloud                1.0.375     
docplex                2.10.154    
EditorConfig           0.12.1      
entrypoints            0.3         
fastdtw                0.3.2       
h5py                   2.9.0       
httplib2               0.11.3      
idna                   2.6         
importlib-metadata     0.19        
inflection             0.3.1       
ipykernel              5.1.1       
ipython                7.6.1       
ipython-genutils       0.2.0       
ipywidgets             7.5.0       
itypes                 1.1.0       
jedi                   0.14.1      
Jinja2                 2.10.1      
joblib                 0.13.2      
jsbeautifier           1.6.4       
jsonschema             2.6.0       
jupyter                1.0.0       
jupyter-client         5.3.1       
jupyter-console        6.0.0       
jupyter-core           4.5.0       
keyring                17.1.1      
keyrings.alt           3.1.1       
kiwisolver             1.1.0       
language-selector      0.1         
launchpadlib           1.10.6      
lazr.restfulclient     0.14.2      
lazr.uri               1.0.3       
louis                  3.8.0       
macaroonbakery         1.2.1       
Mako                   1.0.7       
MarkupSafe             1.1.0       
marshmallow            2.19.5      
marshmallow-polyfield  3.2         
matplotlib             3.1.1       
mistune                0.8.4       
more-itertools         5.0.0       
mpmath                 1.1.0       
nbconvert              5.5.0       
nbformat               4.4.0       
nbimporter             0.3.1       
ndg-httpsclient        0.5.1       
nest-asyncio           1.0.0       
netifaces              0.10.4      
networkx               2.3         
ninja                  1.9.0.post1 
notebook               6.0.0       
ntlm-auth              1.3.0       
numpy                  1.16.4      
oauthlib               2.1.0       
olefile                0.46        
packaging              19.1        
pandas                 0.25.0      
pandocfilters          1.4.2       
parso                  0.5.1       
pexpect                4.6.0       
pickleshare            0.7.5       
Pillow                 5.4.1       
pip                    18.1        
pkg-resources          0.0.0       
pluggy                 0.12.0      
ply                    3.11        
prometheus-client      0.7.1       
prompt-toolkit         2.0.9       
protobuf               3.6.1       
psutil                 5.6.3       
ptyprocess             0.6.0       
py                     1.8.0       
pyasn1                 0.4.6       
pycairo                1.16.2      
pycrypto               2.6.1       
pycups                 1.9.73      
Pygments               2.4.2       
PyGObject              3.32.0      
PyJWT                  1.7.0       
pylatexenc             1.5         
pymacaroons            0.13.0      
PyNaCl                 1.3.0       
pyOpenSSL              19.0.0      
pyparsing              2.4.2       
pyRFC3339              1.1         
pyscf                  1.6.3       
pytest                 5.1.1       
python-apt             1.8.4       
python-dateutil        2.7.3       
python-debian          0.1.34      
pytz                   2018.9      
pyxdg                  0.25        
PyYAML                 3.13        
pyzmq                  18.0.2      
qiskit-aer             0.3.0       /home/jwoehr/work/Qiskit/DEV/qiskit-aer            
qiskit-aqua            0.5.6       /home/jwoehr/work/Qiskit/DEV/qiskit-aqua           
qiskit-aqua-interfaces 0.1.1       /home/jwoehr/work/Qiskit/DEV/qiskit-aqua-interfaces
qiskit-ibmq-provider   0.3.2rc1    /home/jwoehr/work/Qiskit/DEV/qiskit-ibmq-provider  
qiskit-ignis           0.2.0       /home/jwoehr/work/Qiskit/DEV/qiskit-ignis          
qiskit-terra           0.10.0      /home/jwoehr/work/Qiskit/DEV/qiskit-terra          
qtconsole              4.5.2       
Quandl                 3.4.8       
quantuminspire         1.0.0       /home/jwoehr/work/Qiskit/quantuminspire/src        
reportlab              3.5.18      
requests               2.21.0      
requests-ntlm          1.1.0       
requests-unixsocket    0.1.5       
scikit-learn           0.21.3      
scipy                  1.3.0       
SecretStorage          2.3.1       
Send2Trash             1.5.0       
setuptools             40.8.0      
simplejson             3.16.0      
six                    1.12.0      
sklearn                0.0         
ssh-import-id          5.7         
sympy                  1.4         
system-service         0.3         
systemd-python         234         
terminado              0.8.2       
testpath               0.4.2       
tornado                6.0.3       
traitlets              4.3.2       
ubuntu-advantage-tools 19.2        
ubuntu-drivers-common  0.0.0       
ufw                    0.36        
unattended-upgrades    0.1         
uritemplate            3.0.0       
urllib3                1.24.1      
usb-creator            0.3.3       
wadllib                1.3.3       
wcwidth                0.1.7       
webencodings           0.5.1       
websockets             7.0         
wheel                  0.32.3      
widgetsnbextension     3.5.0       
xkit                   0.0.0       
zipp                   0.6.0   
```
* anything else that might be relevant

**Comment by QFer** [comment]
There was a change in the latest qiskit-terra version that introduced this issue. We released quantuminspire version 1.1.0 with a fix for it. After upgrading your version of quantuminspire to 1.1.0 this issue should be solved.
